Update update.yml

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -16,23 +16,34 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
           path: ./repo
 
+      - name: Change directory to repo
+        run: cd ./repo
+
       - name: Add upstream remote
         run: |
+          cd ./repo
           git remote add upstream https://github.com/strawberrymusicplayer/strawberry || echo "Upstream remote already exists."
 
       - name: Fetch upstream changes
-        run: git fetch upstream
+        run: |
+          cd ./repo
+          git fetch upstream
 
       - name: Check out master branch
-        run: git checkout master
+        run: |
+          cd ./repo
+          git checkout master
 
       - name: Check for changes
         id: check_changes
         run: |
+          cd ./repo
           git merge upstream/master --strategy-option=theirs -- . ':!/.github/workflows' || echo "No changes to merge."
 
       - name: Push changes if any
         if: steps.check_changes.outcome == 'success'
-        run: git push origin master || echo "Push failed, no changes to push."
+        run: |
+          cd ./repo
+          git push origin master || echo "Push failed, no changes to push."
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
