Update update.yml

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -17,19 +17,22 @@ jobs:
           path: ./repo
 
       - name: Add upstream remote
-        run: git remote add upstream https://github.com/strawberrymusicplayer/strawberry || echo "Upstream remote already exists."
+        run: |
+          git remote add upstream https://github.com/strawberrymusicplayer/strawberry || echo "Upstream remote already exists."
 
       - name: Fetch upstream changes
         run: git fetch upstream
 
+      - name: Check out master branch
+        run: git checkout master
+
       - name: Check for changes
         id: check_changes
         run: |
-          git checkout main
-          git merge upstream/main --strategy-option=theirs -- . ':!/.github/workflows' || echo "No changes to merge."
+          git merge upstream/master --strategy-option=theirs -- . ':!/.github/workflows' || echo "No changes to merge."
 
       - name: Push changes if any
         if: steps.check_changes.outcome == 'success'
-        run: git push origin main || echo "Push failed, no changes to push."
+        run: git push origin master || echo "Push failed, no changes to push."
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
